[2025-05-05T09:50:28.618+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-05T09:50:28.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-05T09:50:23.548536+00:00 [queued]>
[2025-05-05T09:50:28.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-05T09:50:23.548536+00:00 [queued]>
[2025-05-05T09:50:28.647+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-05T09:50:28.655+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data_into_trino> on 2025-05-05 09:50:23.548536+00:00
[2025-05-05T09:50:28.660+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2025-05-05T09:50:28.661+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'insert_data_into_trino', 'manual__2025-05-05T09:50:23.548536+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpua19jo_3']
[2025-05-05T09:50:28.662+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask insert_data_into_trino
[2025-05-05T09:50:28.689+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-05T09:50:23.548536+00:00 [running]> on host 92b88004addd
[2025-05-05T09:50:28.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='insert_data_into_trino' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T09:50:23.548536+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T09:50:23.548536+00:00'
[2025-05-05T09:50:28.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-05T09:50:29.658+0000] {dbapi.py:285} WARNING - EXECUTE IMMEDIATE not available for trino:8080; defaulting to legacy prepared statements (TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:19: mismatched input ''SELECT 1''. Expecting: 'USING', <EOF>", query_id=20250505_095028_00005_b4a46))
[2025-05-05T09:50:34.035+0000] {logging_mixin.py:188} INFO - Dados inseridos com sucesso nas tabelas Iceberg
[2025-05-05T09:50:34.038+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-05T09:50:34.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-05T09:50:34.048+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_iceberg_example, task_id=insert_data_into_trino, run_id=manual__2025-05-05T09:50:23.548536+00:00, execution_date=20250505T095023, start_date=20250505T095028, end_date=20250505T095034
[2025-05-05T09:50:34.080+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-05T09:50:34.081+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
