[2025-05-04T18:51:00.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T18:51:00.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-04T18:50:57.523020+00:00 [queued]>
[2025-05-04T18:51:00.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-04T18:50:57.523020+00:00 [queued]>
[2025-05-04T18:51:00.501+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-04T18:51:00.510+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-05-04 18:50:57.523020+00:00
[2025-05-04T18:51:00.515+0000] {standard_task_runner.py:63} INFO - Started process 780 to run task
[2025-05-04T18:51:00.518+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'dbt_debug', 'manual__2025-05-04T18:50:57.523020+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpyix888fr']
[2025-05-04T18:51:00.519+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask dbt_debug
[2025-05-04T18:51:00.558+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-04T18:50:57.523020+00:00 [running]> on host 27fc0593f179
[2025-05-04T18:51:00.617+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T18:50:57.523020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T18:50:57.523020+00:00'
[2025-05-04T18:51:00.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T18:51:00.626+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T18:51:00.627+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir .']
[2025-05-04T18:51:00.637+0000] {subprocess.py:86} INFO - Output:
[2025-05-04T18:51:03.167+0000] {subprocess.py:93} INFO - [0m18:51:03  Running with dbt=1.7.0
[2025-05-04T18:51:03.170+0000] {subprocess.py:93} INFO - [0m18:51:03  dbt version: 1.7.0
[2025-05-04T18:51:03.171+0000] {subprocess.py:93} INFO - [0m18:51:03  python version: 3.10.14
[2025-05-04T18:51:03.172+0000] {subprocess.py:93} INFO - [0m18:51:03  python path: /home/***/.local/bin/python
[2025-05-04T18:51:03.172+0000] {subprocess.py:93} INFO - [0m18:51:03  os info: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-05-04T18:51:03.281+0000] {subprocess.py:93} INFO - [0m18:51:03  Using profiles dir at .
[2025-05-04T18:51:03.283+0000] {subprocess.py:93} INFO - [0m18:51:03  Using profiles.yml file at ./profiles.yml
[2025-05-04T18:51:03.283+0000] {subprocess.py:93} INFO - [0m18:51:03  Using dbt_project.yml file at /opt/***/dbt_project/dbt_project.yml
[2025-05-04T18:51:03.284+0000] {subprocess.py:93} INFO - [0m18:51:03  adapter type: trino
[2025-05-04T18:51:03.285+0000] {subprocess.py:93} INFO - [0m18:51:03  adapter version: 1.7.0
[2025-05-04T18:51:03.350+0000] {subprocess.py:93} INFO - [0m18:51:03  Configuration:
[2025-05-04T18:51:03.351+0000] {subprocess.py:93} INFO - [0m18:51:03    profiles.yml file [[32mOK found and valid[0m]
[2025-05-04T18:51:03.352+0000] {subprocess.py:93} INFO - [0m18:51:03    dbt_project.yml file [[32mOK found and valid[0m]
[2025-05-04T18:51:03.353+0000] {subprocess.py:93} INFO - [0m18:51:03  Required dependencies:
[2025-05-04T18:51:03.365+0000] {subprocess.py:93} INFO - [0m18:51:03   - git [[32mOK found[0m]
[2025-05-04T18:51:03.366+0000] {subprocess.py:93} INFO - 
[2025-05-04T18:51:03.366+0000] {subprocess.py:93} INFO - [0m18:51:03  Connection:
[2025-05-04T18:51:03.367+0000] {subprocess.py:93} INFO - [0m18:51:03    host: trino
[2025-05-04T18:51:03.368+0000] {subprocess.py:93} INFO - [0m18:51:03    port: 8080
[2025-05-04T18:51:03.369+0000] {subprocess.py:93} INFO - [0m18:51:03    user: ***
[2025-05-04T18:51:03.370+0000] {subprocess.py:93} INFO - [0m18:51:03    database: iceberg
[2025-05-04T18:51:03.370+0000] {subprocess.py:93} INFO - [0m18:51:03    schema: default
[2025-05-04T18:51:03.371+0000] {subprocess.py:93} INFO - [0m18:51:03    cert: None
[2025-05-04T18:51:03.372+0000] {subprocess.py:93} INFO - [0m18:51:03    prepared_statements_enabled: True
[2025-05-04T18:51:03.373+0000] {subprocess.py:93} INFO - [0m18:51:03  Registered adapter: trino=1.7.0
[2025-05-04T18:51:03.751+0000] {subprocess.py:93} INFO - [0m18:51:03    Connection test: [[32mOK connection ok[0m]
[2025-05-04T18:51:03.751+0000] {subprocess.py:93} INFO - 
[2025-05-04T18:51:03.752+0000] {subprocess.py:93} INFO - [0m18:51:03  [32mAll checks passed![0m
[2025-05-04T18:51:04.767+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-04T18:51:04.768+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T18:51:04.784+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_iceberg_example, task_id=dbt_debug, run_id=manual__2025-05-04T18:50:57.523020+00:00, execution_date=20250504T185057, start_date=20250504T185100, end_date=20250504T185104
[2025-05-04T18:51:04.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-04T18:51:04.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
